name: Publish New Release
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: make dist
      run: mkdir dist

    - name: build
      run: go build -ldflags "-s -w" -o dist ./...
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - name: additional items
      run: cp README.md dist/

    - name: Zip Folder
      if: ${{ matrix.goos == 'windows'}}
      run: zip -r ../release.zip ./
      working-directory: dist

    - name: Tar Folder
      if: ${{ matrix.goos != 'windows'}}
      run: tar czf ../release.tgz ./
      working-directory: dist

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: commands-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.goos == 'windows' && 'zip' || 'tgz' }}
        asset_path: ${{ matrix.goos == 'windows' && 'release.zip' || 'release.tgz' }}
        asset_content_type: application/octet-stream
